apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: web-app-template
  title: Web Application Template
  description: Scaffolds a web application
  tags:
    - web
spec:
  owner: your-team@example.com
  parameters:
    - title: Repository Configuration
      required:
        - repoName
        - repoVisibility
      properties:
        repoName:
          type: string
          description: The name of the GitHub repository
        repoVisibility:
          type: string
          description: The visibility of the repository
          enum:
            - public
            - private
  steps:
    - id: generate-web-app
      name: Generate Web Application
      action: templater:handlebars
      input:
        files:
          - ./skeleton/**
        values:
          appName: "WebApp"
    - id: output-repo-info
      name: Output Repository Info
      action: scaffolder:output
      input:
        repoUrl: https://github.com/rohit753/${{ parameters.repoName }}
  output:
    repoUrl: ${{ steps.output-repo-info.outputs.repoUrl }}
