name: 'Terraform Deploy'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Terraform Cloud Workspace
      id: create_workspace
      run: |
        curl \
          --header "Authorization: Bearer ${{ secrets.TF_API_TOKEN }}" \
          --header "Content-Type: application/vnd.api+json" \
          --request POST \
          --data '{
            "data": {
              "attributes": {
                "name": "YOUR_WORKSPACE_NAME",
                "organization": "YOUR_ORGANIZATION_NAME"
              },
              "type": "workspaces"
            }
          }' \
          https://app.terraform.io/api/v2/organizations/YOUR_ORGANIZATION_NAME/workspaces

    - name: Terraform Init
      run: terraform init
      env:
        TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}