apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: microservice-template
  title: Microservice Template
  description: Scaffolds a microservice
  tags:
    - microservice
spec:
  owner: your-team@example.com
  parameters:
    - title: Repository Configuration
      required:
        - repoName
        - repoVisibility
      properties:
        repoName:
          type: string
          description: The name of the GitHub repository
        repoVisibility:
          type: string
          description: The visibility of the repository
          enum:
            - public
            - private
  steps:
    - id: generate-microservice
      name: Generate Microservice
      action: templater:handlebars
      input:
        files:
          - - .skeleton/**
        values:
          appName: "Microservice"
    - id: output-repo-info
      name: Output Repository Info
      action: scaffolder:output
      input:
        repoUrl: https://github.com/example/${{ parameters.repoName }}
  output:
    repoUrl: ${{ steps.output-repo-info.outputs.repoUrl }}
