apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name:  ${{ values.name | dump }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.owner + "/" + values.name }}
spec:
  type: service
  owner: ${{values.owner | dump}}
  lifecycle: production
